# Inspect openid configuration (hydra):
#     curl localhost:4444/.well-known/openid-configuration | jq

version: '3.7'
services:

  nginx:
    depends_on:
      - kratos
      - kratos-selfservice-ui-node
      - hydra
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    volumes:
      - ./reverse-proxy/landing-page:/usr/share/nginx/html:ro
      - ./reverse-proxy/id.conf:/etc/nginx/conf.d/id.conf:ro
      - ./reverse-proxy/petadvisor.conf:/etc/nginx/conf.d/petadvisor.conf:ro
      - ./reverse-proxy/oauth.conf:/etc/nginx/conf.d/oauth.conf:ro
      - ./reverse-proxy/app.petadvisor_am.conf:/etc/nginx/conf.d/app.petadvisor.conf:ro
      - ./reverse-proxy/data.petadvisor.conf:/etc/nginx/conf.d/data.petadvisor.conf:ro
    networks:
      intranet:
        ipv4_address: 172.30.0.2

  kratos-migrate:
    image: oryd/kratos:v1.3.1
    user: 10000:101
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: bind
        source: ./kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos/quickstart/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    ports:
      - "4455:4455"
    environment:
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - KRATOS_PUBLIC_URL=http://id.petadvisor.internal/
      - KRATOS_BROWSER_URL=http://id.petadvisor.internal/
    restart: on-failure
    networks:
      intranet:
        aliases:
          - kratos-ui

  kratos:
    depends_on:
      - kratos-migrate
      - mailpit
    image: oryd/kratos:v1.3.1
    user: 10000:101
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
      - KRATOS_PUBLIC_URL=http://127.0.0.1:4433/
      - KRATOS_ADMIN_URL=http://127.0.0.1:4434/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos/quickstart/kratos/email-password
        target: /etc/config/kratos
    networks:
      - intranet

  mailpit:
    image: axllent/mailpit
    user: 1000:1000
    ports:
      - '127.0.0.1:8025:8025'
      - '127.0.0.1:1025:1025'
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped
    volumes:
      - ./mailpit:/data
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v2.2.0
    # Run docker run --rm -it --entrypoint='' oryd/hydra:v2.2.0 id to find the default uid:gid
    user: 10000:101
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./hydra-contrib
        target: /etc/config/hydra
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    user: 10000:101
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./hydra-contrib
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

  consent-ui:
      image: docker.io/oryd/hydra-login-consent-node:latest-custom
      user: "10000:101"
      restart: unless-stopped
      ports:
        - "3000:3000"
      environment:
        - HYDRA_ADMIN_URL=http://hydra:4445/
        - KRATOS_ADMIN_URL=http://kratos:4434
      networks:
        - intranet

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    volumes:
      - type: bind
        #source: ./oauth2-proxy/oauth2-proxy.cfg
        source: ./oauth2-proxy/oauth2-am.cfg
        target: /oauth2-proxy.cfg
        read_only: true
    command: --config /oauth2-proxy.cfg
    restart: on-failure
    network_mode: host

  envoy:
    image: envoyproxy/envoy:debug-dev
    command:
      - --config-path /etc/envoy/envoy.yaml
      - --log-level debug
    volumes:
      - type: bind
        source: ./envoy/envoy_am.yaml
        target: /etc/envoy/envoy.yaml
        read_only: true
    network_mode: host


  minio:
    image: quay.io/minio/minio:latest
    user: 1000:1000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - type: bind
        source: ./minio/data
        target: /data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    restart: on-failure
    networks:
      intranet:
        aliases:
          - minio

networks:
  intranet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
          ip_range: 172.30.0.96/28
