# Inspect openid configuration (hydra):
#     curl localhost:4444/.well-known/openid-configuration | jq

version: '3.7'
services:

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    volumes:
      - type: bind
        source: ./oauth2-proxy/oauth2-proxy.cfg
        target: /oauth2-proxy.cfg
        read_only: true
    command: --config /oauth2-proxy.cfg
    network_mode: host

networks:
  intranet:

