// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/weight.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeightServiceClient is the client API for WeightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeightServiceClient interface {
	CreateWeightMeasurement(ctx context.Context, in *CreateWeightMeasurementRequest, opts ...grpc.CallOption) (*WeightMeasurement, error)
}

type weightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeightServiceClient(cc grpc.ClientConnInterface) WeightServiceClient {
	return &weightServiceClient{cc}
}

func (c *weightServiceClient) CreateWeightMeasurement(ctx context.Context, in *CreateWeightMeasurementRequest, opts ...grpc.CallOption) (*WeightMeasurement, error) {
	out := new(WeightMeasurement)
	err := c.cc.Invoke(ctx, "/weights.WeightService/CreateWeightMeasurement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightServiceServer is the server API for WeightService service.
// All implementations must embed UnimplementedWeightServiceServer
// for forward compatibility
type WeightServiceServer interface {
	CreateWeightMeasurement(context.Context, *CreateWeightMeasurementRequest) (*WeightMeasurement, error)
	mustEmbedUnimplementedWeightServiceServer()
}

// UnimplementedWeightServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeightServiceServer struct {
}

func (UnimplementedWeightServiceServer) CreateWeightMeasurement(context.Context, *CreateWeightMeasurementRequest) (*WeightMeasurement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWeightMeasurement not implemented")
}
func (UnimplementedWeightServiceServer) mustEmbedUnimplementedWeightServiceServer() {}

// UnsafeWeightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeightServiceServer will
// result in compilation errors.
type UnsafeWeightServiceServer interface {
	mustEmbedUnimplementedWeightServiceServer()
}

func RegisterWeightServiceServer(s grpc.ServiceRegistrar, srv WeightServiceServer) {
	s.RegisterService(&WeightService_ServiceDesc, srv)
}

func _WeightService_CreateWeightMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWeightMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightServiceServer).CreateWeightMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weights.WeightService/CreateWeightMeasurement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightServiceServer).CreateWeightMeasurement(ctx, req.(*CreateWeightMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeightService_ServiceDesc is the grpc.ServiceDesc for WeightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weights.WeightService",
	HandlerType: (*WeightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWeightMeasurement",
			Handler:    _WeightService_CreateWeightMeasurement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/weight.proto",
}
